# Generated by Django 5.1.7 on 2026-03-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50, verbose_name="การกระทำ")),
                ("detail", models.TextField(verbose_name="รายละเอียด")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="เวลา"),
                ),
            ],
            options={
                "verbose_name": "ประวัติการดำเนินการ",
                "verbose_name_plural": "ประวัติการดำเนินการ",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="TrainingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emp_name",
                    models.CharField(max_length=255, verbose_name="ชื่อพนักงาน"),
                ),
                ("emp_id", models.CharField(max_length=50, verbose_name="รหัสพนักงาน")),
                (
                    "course",
                    models.CharField(max_length=255, verbose_name="ชื่อหลักสูตร"),
                ),
                (
                    "trainer",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="วิทยากร / ผู้สอน",
                    ),
                ),
                ("train_date", models.DateField(verbose_name="วันที่อบรม")),
                (
                    "score",
                    models.FloatField(blank=True, null=True, verbose_name="คะแนน"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ผ่าน", "ผ่าน"),
                            ("ไม่ผ่าน", "ไม่ผ่าน"),
                            ("รอผล", "รอผล"),
                        ],
                        default="ผ่าน",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อมูลการฝึกอบรม",
                "verbose_name_plural": "ข้อมูลการฝึกอบรม",
                "ordering": ["-id"],
            },
        ),
    ]
