# Generated by Django 6.0.3 on 2026-03-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("ผ่าน", "✅ ผ่าน"),
                    ("ไม่ผ่าน", "❌ ไม่ผ่าน"),
                    ("รอผล", "⏳ รอผล"),
                ],
                default="ผ่าน",
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
    ]
